import io
import datetime
from typing import Dict, Any, List

def generate_scientific_pdf_report(
    title: str,
    study_region: str,
    generated_by: str,
    summary_metrics: Dict[str, Any],
    zones_included: List[Dict[str, Any]],
    include_sections: List[str],
    custom_notes: str = ""
) -> bytes:
    """
    Generates a formal research-grade PDF report using ReportLab.
    """
    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.lib import colors
        from reportlab.lib.units import inch
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=36,
            leftMargin=36,
            topMargin=36,
            bottomMargin=36
        )
        
        styles = getSampleStyleSheet()
        
        # Custom palette styles
        primary_color = colors.HexColor("#0f766e") # teal-700
        secondary_color = colors.HexColor("#0284c7") # sky-600
        dark_text = colors.HexColor("#0f172a") # slate-900
        light_bg = colors.HexColor("#f8fafc") # slate-50
        border_color = colors.HexColor("#cbd5e1")
        
        title_style = ParagraphStyle(
            'DocTitle',
            parent=styles['Heading1'],
            fontName='Helvetica-Bold',
            fontSize=18,
            leading=22,
            textColor=primary_color,
            spaceAfter=4
        )
        subtitle_style = ParagraphStyle(
            'DocSub',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=10,
            leading=14,
            textColor=colors.HexColor("#475569"),
            spaceAfter=12
        )
        h2_style = ParagraphStyle(
            'SectionH2',
            parent=styles['Heading2'],
            fontName='Helvetica-Bold',
            fontSize=13,
            leading=16,
            textColor=primary_color,
            spaceBefore=10,
            spaceAfter=6
        )
        body_style = ParagraphStyle(
            'Body',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=9,
            leading=13,
            textColor=dark_text
        )
        callout_style = ParagraphStyle(
            'Callout',
            parent=styles['Normal'],
            fontName='Helvetica-Oblique',
            fontSize=8.5,
            leading=12,
            textColor=colors.HexColor("#334155")
        )
        
        elements = []
        
        # Header
        elements.append(Paragraph("GANGA BIOCIRCULARITY INTELLIGENCE PLATFORM", title_style))
        elements.append(Paragraph(f"<b>Scientific Assessment & Resource Recovery Report</b> | Region: {study_region}", subtitle_style))
        elements.append(HRFlowable(width="100%", thickness=1.5, color=primary_color, spaceBefore=2, spaceAfter=10))
        
        # Metadata Bar Table
        meta_data = [
            [
                Paragraph(f"<b>Date:</b> {datetime.datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}", body_style),
                Paragraph(f"<b>Generated By:</b> {generated_by}", body_style),
                Paragraph(f"<b>Data Mode:</b> Prototype / Research Feed", body_style),
                Paragraph(f"<b>Classification Model:</b> v2.4-Sentinel-2", body_style)
            ]
        ]
        meta_table = Table(meta_data, colWidths=[130, 130, 140, 140])
        meta_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), light_bg),
            ('BOX', (0, 0), (-1, -1), 0.5, border_color),
            ('INNERGRID', (0, 0), (-1, -1), 0.5, border_color),
            ('TOPPADDING', (0, 0), (-1, -1), 4),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ]))
        elements.append(meta_table)
        elements.append(Spacer(1, 10))
        
        # Executive Summary / Key Metrics Grid
        elements.append(Paragraph("1. Executive Summary & Key Indicators", h2_style))
        
        summary_table_data = [
            [
                Paragraph("<b>Hyacinth Coverage</b>", body_style),
                Paragraph(f"{summary_metrics.get('total_coverage_ha', 38.6)} ha", body_style),
                Paragraph("<b>Total Fresh Biomass</b>", body_style),
                Paragraph(f"{summary_metrics.get('total_fresh_biomass_t', 1170.4)} tonnes", body_style)
            ],
            [
                Paragraph("<b>Estimated Dry Solids (TS)</b>", body_style),
                Paragraph(f"{summary_metrics.get('total_dry_solids_t', 105.3)} tonnes", body_style),
                Paragraph("<b>Bio-CNG Potential</b>", body_style),
                Paragraph(f"{summary_metrics.get('bio_cng_potential_kg', 16840):,} kg", body_style)
            ],
            [
                Paragraph("<b>Vermicompost Yield</b>", body_style),
                Paragraph(f"{summary_metrics.get('vermicompost_t', 23.7)} tonnes", body_style),
                Paragraph("<b>Circularity Score</b>", body_style),
                Paragraph(f"<b>{summary_metrics.get('circularity_score', 81.4)} / 100</b>", body_style)
            ],
            [
                Paragraph("<b>GHG Avoidance (LCA)</b>", body_style),
                Paragraph(f"{summary_metrics.get('ghg_avoidance_kg', 121400):,} kg CO₂e", body_style),
                Paragraph("<b>Net Economic Benefit</b>", body_style),
                Paragraph(f"₹ {summary_metrics.get('net_benefit_inr', 485000):,}", body_style)
            ]
        ]
        
        sum_table = Table(summary_table_data, colWidths=[140, 130, 140, 130])
        sum_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), colors.white),
            ('BOX', (0, 0), (-1, -1), 0.5, border_color),
            ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ('TOPPADDING', (0, 0), (-1, -1), 5),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ]))
        elements.append(sum_table)
        elements.append(Spacer(1, 10))
        
        # Spatial Monitoring & Zones
        elements.append(Paragraph("2. Spatial Distribution & Detected Hyacinth Zones", h2_style))
        zone_rows = [
            [
                Paragraph("<b>Zone Code</b>", body_style),
                Paragraph("<b>Location / Reach</b>", body_style),
                Paragraph("<b>Density Class</b>", body_style),
                Paragraph("<b>Area (ha)</b>", body_style),
                Paragraph("<b>Biomass (t)</b>", body_style),
                Paragraph("<b>Confidence</b>", body_style)
            ]
        ]
        
        for z in zones_included:
            zone_rows.append([
                Paragraph(z.get("zone_code", "HZ-01"), body_style),
                Paragraph(z.get("name", "Sangam Reach")[:26], body_style),
                Paragraph(z.get("density_class", "High"), body_style),
                Paragraph(str(z.get("area_ha", 10.0)), body_style),
                Paragraph(str(z.get("fresh_biomass_t", 320.0)), body_style),
                Paragraph(f"{int(z.get('confidence', 0.90) * 100)}%", body_style)
            ])
            
        zone_table = Table(zone_rows, colWidths=[70, 170, 80, 65, 75, 80])
        zone_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#f1f5f9")),
            ('BOX', (0, 0), (-1, -1), 0.5, border_color),
            ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ('TOPPADDING', (0, 0), (-1, -1), 4),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ]))
        elements.append(zone_table)
        elements.append(Spacer(1, 10))
        
        # Resource Recovery & Bioenergy
        elements.append(Paragraph("3. Bioenergy, Vermicompost & Circular Transformation", h2_style))
        elements.append(Paragraph(
            "Anaerobic Digestion is modeled at mesophilic temperatures (37°C) using Continuous Stirred-Tank Reactor (CSTR) dynamics. "
            "Volatile solids degradation yields biomethane (CH₄ ~62%) compressed into Bio-CNG for transport/cooking displacement. "
            "Separated digestate solids undergo vermicomposting with <i>Eisenia foetida</i> to yield high-grade organic fertilizer and vermiwash.",
            body_style
        ))
        elements.append(Spacer(1, 6))
        
        # Environmental and Economics
        elements.append(Paragraph("4. Environmental Impact & Techno-Economic Feasibility", h2_style))
        elements.append(Paragraph(
            f"Clearing invasive water hyacinth mats restores dissolved oxygen levels across {summary_metrics.get('total_coverage_ha', 38.6)} ha of river surface, "
            f"diverts {summary_metrics.get('total_fresh_biomass_t', 1170.4)} tonnes of rotting aquatic biomass, and avoids {summary_metrics.get('ghg_avoidance_kg', 121400):,} kg CO₂e in greenhouse gas emissions.",
            body_style
        ))
        elements.append(Spacer(1, 6))
        
        # Methodology & Limitations
        elements.append(Paragraph("5. Scientific Methodology, Data Provenance & Limitations", h2_style))
        elements.append(Paragraph(
            "<b>Methodology:</b> Multi-index spectral fusion (NDVI ≥ 0.38 combined with MNDWI water masking) from Sentinel-2 MSI Level-2A imagery. "
            "Biomass calculated using allometric area-to-yield empirical density coefficients (17-35 t/ha fresh basis).<br/>"
            "<b>Limitations:</b> Remote sensing estimates are constrained by cloud cover and mixed-pixel water-vegetation boundaries. "
            "Heavy metal uptake and pathogen counts must be validated through wet-chemical laboratory analysis prior to commercial agricultural fertilizer distribution.",
            callout_style
        ))
        
        if custom_notes:
            elements.append(Spacer(1, 6))
            elements.append(Paragraph(f"<b>Analyst Custom Notes:</b> {custom_notes}", body_style))
            
        doc.build(elements)
        pdf_data = buffer.getvalue()
        buffer.close()
        return pdf_data
    except Exception as e:
        # Simple PDF fallback string in binary format if reportlab is unavailable
        fallback_text = f"%PDF-1.4\n1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj 2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj 3 0 obj<</Type/Page/MediaBox[0 0 612 792]/Parent 2 0 R/Resources<<>>>>endobj\nxref\n0 4\n0000000000 65535 f\n0000000009 00000 n\n0000000052 00000 n\n0000000101 00000 n\ntrailer<</Size 4/Root 1 0 R>>\nstartxref\n178\n%%EOF"
        return fallback_text.encode("utf-8")
